apply plugin: 'com.android.application'\n\nandroid {\n    compileSdkVersion 33\n    sourceCompatibility JavaVersion.VERSION_1_8\n    targetCompatibility JavaVersion.VERSION_1_8\n\n    defaultConfig {\n        applicationId "com.example.fanyi_app"\n        minSdkVersion 21\n        targetSdkVersion 33\n        versionCode 1\n        versionName "1.0"\n    }\n    buildTypes {\n        release {\n            minifyEnabled false\n            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'\n        }\n    }\n}\n\ndependencies {\n    implementation 'com.google.firebase:firebase-analytics-ktx:21.0.0'\n    implementation 'androidx.appcompat:appcompat:1.4.1'\n    implementation 'androidx.core:core-ktx:1.7.0'\n    // Other dependencies\n}